---
- hosts: localhost
become: true
vars:
docker_image_name: toncompte/tonimage
docker_image_tag: latest
container_name: mon-conteneur
tasks:
- name: Installer Docker (si pas déjà fait)
apt:
name: docker.io
state: present
when: ansible_distribution == "Ubuntu"

- name: Installer la collection community.docker (pour gérer Docker)
ansible.builtin.command: ansible-galaxy collection install community.docker
args:
creates: /root/.ansible/collections/ansible_collections/community/docker

- name: Télécharger l'image Docker depuis Docker Hub
community.docker.docker_image:
name: "{{ geraldh443/citation }}"
tag: "{{ latest}}"
source: pull

- name: Démarrer le conteneur
community.docker.docker_container:
name: "{{ Deploy}}"
image: "{{geraldh443/citation }}:{{latest }}"
state: started
ports:
- "80:80"
